version: '2.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
        - ./mysql_volumes:/var/lib/mysql
    networks:
      backend:
        aliases:
          - "db"
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: ostock/eureka:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    depends_on:
      db:
        condition: service_healthy
      configserver:
        condition: service_started  
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      # CONFIGSERVER_URI: "http://configserver:8071"
      # EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      CONFIGSERVER_URI: "http://localhost:8071"
      EUREKASERVER_URI: "http://localhost:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      db:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"
  licensingservice:
    image: ostock/microservice_licensing:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      # CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_URI: "http://localhost:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      db:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
      - "8180:8080"
    networks:
      - backend
  organizationservice:
    image: ostock/microservice_organization:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      # CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_URI: "http://localhost:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      db:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

  keycloak:
    image: alemairebe/keycloak:14.0.0
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # JAVA_OPTS: "-Djboss.as.management.blocking.timeout = 6000"
      JAVA_OPTS_APPEND: "-Djboss.as.management.blocking.timeout=7200"
    volumes:
        - ./realm-export.json:/opt/alemairebe/keycloak/realm-export.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/alemairebe/keycloak/realm-export.json"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

networks:
  backend:
    driver: bridge